name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  issues: none
  pull-requests: none

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run lint
    if: github.repository == 'skyclouds2001/vite-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm lint
  tests:
    name: Run test
    if: github.repository == 'skyclouds2001/vite-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
      - name: Upload test report
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-report
          path: |
            vitest-report/
            coverage-report/
